wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: mnist
hidden_layers:
  value: 3
learning_rate:
  value: 0.01
num_neurons:
  value: 64
optimizer:
  value: rmsprop
weight_init:
  value: random
